# Generated by Django 5.2.2 on 2025-06-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infouser',
            name='name',
            field=models.CharField(max_length=255, verbose_name='edfwef'),
        ),
    ]
