# Generated by Django 5.2.2 on 2025-06-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_infouser_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infouser',
            options={'verbose_name': 'Информация о пользователе', 'verbose_name_plural': 'Информация о пользователях'},
        ),
        migrations.AddField(
            model_name='infouser',
            name='description',
            field=models.TextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infouser',
            name='github',
            field=models.URLField(default=1, verbose_name='Гитхаб'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infouser',
            name='image',
            field=models.ImageField(default=1, upload_to='infouser/', verbose_name='Фотография'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infouser',
            name='linkedin',
            field=models.URLField(default=1, verbose_name='Линкед Ин'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infouser',
            name='telegram',
            field=models.URLField(default=1, verbose_name='Телеграм'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infouser',
            name='twitter',
            field=models.URLField(default=1, verbose_name='Твиттер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infouser',
            name='work',
            field=models.CharField(default=1, max_length=255, verbose_name='Работа'),
            preserve_default=False,
        ),
    ]
