# Generated by Django 5.2.2 on 2025-06-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_infouser_options_infouser_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infouser',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
